version: "3"

services:
  elasticsearch:
    container_name: elastic
    build: ./elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - ./mapping:/mapping
      - ./elasticsearch/dict:/usr/share/elasticsearch/config/dict

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.10.0
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

  python3:
    build: ./python3/
    container_name: 'python3'
    tty: true
    command: python3 manage.py runserver 0.0.0.0:8080
    depends_on:
      - elasticsearch
    volumes:
      - ./python3/src:/src
    ports:
      - 8080:8080
